version: 2.1

refs:
  container: &container
    docker:
      - image: node:12.22.1
  steps:
    - &Versions
      run:
        name: Display versions
        command: node -v && npm -v && yarn -v
    - &CacheRestore
      restore_cache:
        name: Restore node modules cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - &Install
      run:
        name: Install dependencies
        command: yarn install --immutable
    - &CacheSave
      save_cache:
        name: Save node modules cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
    - &Build
      run:
        name: Build the package
        command: yarn build
    - &Lint
      run:
        name: Lint code
        command: yarn lint
    - &LintCommits
      run:
        name: Lint commit messages
        command: |
          npx commitlint --from main --to << pipeline.git.revision >>
    - &Test
      run:
        name: Test the package
        command: yarn test
    - &Release
      run:
        name: Release a new version of the package
        command: yarn release
    - &Build_Storybook
      run:
        name: Build Storybook
        command: yarn storybook:build
    - &Commit_Status_Storybook
      run:
        name: Post commit status for Storybook
        command: |
          npx cross-ci :run curl -H "'Authorization: token \${GH_TOKEN}' -H 'Accept: application/vnd.github.v3+json'" \
          "'https://api.github.com/repos/\${PROJECT_OWNER}/\${PROJECT_NAME}/statuses/$CIRCLE_SHA1'" -X POST \
          -d "'{\"state\": \"success\", \"context\": \"Storybook\", \"description\": \"\${BUILD_VERSION}\", \"target_url\": \"https://$CIRCLE_BUILD_NUM-154950925-gh.circle-artifacts.com/0/root/repo/storybook-static/index.html\"}'"
    - &Setup_GitHub
      run:
        name: Setup GitHub
        command: |
          git config --global user.email "dimazuien@gmail.com"
          git config --global user.name "dimazuien"
          git remote rm origin
          git remote add origin https://${GH_TOKEN}@github.com/dimazuien/react-viewport-height
    - &Upload_Storybook
      run:
        name: Upload Storybook
        command: yarn storybook:upload

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *CacheRestore
      - *Install
      - *CacheSave
      - *Test
      - *Lint
      - *LintCommits

  main:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *CacheRestore
      - *Install
      - *CacheSave
      - *Test
      - *Lint
      - *LintCommits
      - *Build
      - *Release
      - *Build_Storybook
      - *Commit_Status_Storybook
      - *Setup_GitHub      
      - *Upload_Storybook

workflows:
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - main
  main:
    jobs:
      - main:
          filters:
            branches:
              only: main
