version: 2.1
orbs:
  node: circleci/node@4.1.0

commands:
  prepare:
    description: 'Check out to a project folder and install/restore packages'
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
jobs:
  lint-code:
    executor: node/default
    steps:
      - prepare
      - run:
          name: Lint code
          command: npm run lint
  lint-commit-message:
    executor: node/default
    steps:
      - prepare
      - run:
          name: Lint commit messages
          command: |
            npx commitlint --from << pipeline.git.base_revision >> --to << pipeline.git.revision >>

workflows:
  commit:
    jobs:
      - lint-code
      - lint-commit-message
