version: 2.1

orbs:
  node: circleci/node@4.1.0

refs:
  container: &container
    docker:
      - image: node:12.20.0

commands:
  prepare:
    description: 'Check out to a project folder and install/restore packages'
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save node modules cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
jobs:
  lint-code:
    <<: *container
    executor: node/default
    steps:
      - prepare
      - run:
          name: Lint code
          command: yarn run lint
  lint-commit-message:
    <<: *container
    executor: node/default
    steps:
      - prepare
      - run:
          name: Lint commit messages
          command: |
            npx commitlint --from main --to << pipeline.git.revision >>
  release:
    <<: *container
    executor: node/default
    steps:
      - prepare
      - run:
          name: Build package
          command: yarn run build
      - run:
          name: Release package
          command: npx semantic-release

workflows:
  release:
    jobs:
      - lint-code
      - lint-commit-message
      - release:
          filters:
            branches:
              only: main
          requires:
            - lint-code
            - lint-commit-message
