version: 2.1

refs:
  container: &container
    docker:
      - image: node:12.20.0
  steps:
    - &Versions
      run:
        name: Display versions
        command: node -v && npm -v && yarn -v
    - &CacheRestore
      restore_cache:
        name: Restore node modules cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - &Install
      run:
        name: Install dependencies
        command: yarn install --immutable
    - &CacheSave
      save_cache:
        name: Save node modules cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
    - &Build
      run:
        name: Build the package
        command: yarn build
    - &Lint
      run:
        name: Lint code
        command: yarn lint
    - &LintCommits
      run:
        name: Lint commit messages
        command: |
          npx commitlint --from main --to << pipeline.git.revision >>
    - &Test
      run:
        name: Test the package
        command: yarn test
    - &Release
      run:
        name: Release a new version of the package
        command: yarn release

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *CacheRestore
      - *Install
      - *CacheSave
      - *Test
      - *Lint
      - *LintCommits

  main:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *CacheRestore
      - *Install
      - *CacheSave
      - *Test
      - *Lint
      - *LintCommits
      - *Build
      - *Release

workflows:
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - main
                - gh-pages
  main:
    jobs:
      - main:
          filters:
            branches:
              only: main
