blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/dimazuien/react-router-scroll-to-top/discussions/new
    about: Ask a question, share an idea, give a feedback
