blank_issues_enabled: false
contact_links:
  - name: 🆘 I need Help
    url: https://github.com/dimazuien/react-router-scroll-to-top/discussions/new
    about: Got a question? An idea? Feedback? Start here.
